### ISSUE TITLE
Not able to install 1.0.0-alpha1 when using Symfony 3.0.x

### ISSUE THREAD

**Issue by wsromek** [ftrrtf/FtrrtfRollbarBundle#24]
When trying to install rollbar-bundle tries to resolve its dependecy on rollbar-notifier using ```^1.0``` version.

This constraint makes composer try to resolve ```1.01, 1.02, 1.03``` and each one of them requires ```symfony/options-resolver >=2.1,<3.0``` while on rollbar-notifier:dev-master the constraint is correct meaning ```symfony/options-resolver" : "~2.6|~3.0"```.

Could you release rollbar-notifier with updated constraint?

**Comment by filipgolonka** [comment]
:+1:

**Comment by arkadiuszmalina** [comment]
:+1:

**Comment by jgarczynski** [comment]
:+1:

**Comment by rafalkanski** [comment]
:+1:

**Comment by ftrrtf** [comment]
Thanks for noticing. I'll fix it.

**Comment by ftrrtf** [comment]
Try with `1.0.0-alpha2`, plz.

**Comment by wsromek** [comment]
@ftrrtf  Though everything looks right, I get ```ftrrtf/rollbar-bundle 1.0.0-alpha2 requires ftrrtf/rollbar-notifier dev-1.0.0-alpha -> no matching package found```. Maybe some cache issues? I'll try again in an hour or so and I'll let you know.

**Comment by ftrrtf** [comment]
@wsromek Looks like just packagist cache, works fine for me

**Comment by wsromek** [comment]
@ftrrtf 
It finally worked but I had to manually require ```rollbar-notifier:dev-1.0.0-alpha``` and only then I was able to install ```rollbar-bundle:1.0.0-alpha2```. 

When done in reverse order I still got the same message as last time.

**Comment by ftrrtf** [comment]
@wsromek yeah, it's because non-stable version used.
`The package is not available in a stable-enough version according to your minimum-stability setting.` 

Just need to specify both libraries: `composer require ftrrtf/rollbar-bundle:1.0.0-alpha3 ftrrtf/rollbar-notifier:2.0.0-alpha1`

**Comment by wsromek** [comment]
The bundle installs ok :+1:, though it seems to be incompatible with Symfony3.x. Didn't have much time to investigate; I'll create a separate issue.
