### ISSUE TITLE
The bundle does not work with Symfony 3.x

### ISSUE THREAD

**Issue by wsromek** [ftrrtf/FtrrtfRollbarBundle#25]
We found that bundle installation under Symfony3.x crashes the app.

Error message:
```PHP Warning: Declaration of Ftrrtf\RollbarBundle\Rollbar\Environment::setDefaultOptions(Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver) should be compatible with Ftrrtf\Rollbar\Environment::setDefaultOptions(Symfony\Component\OptionsResolver\Options $resolver) in /ftrrtf/rollbar-bundle/Rollbar/Environment.php on line 13```

We did not have time to investigate it any further so sorry, but this is all we got.

**Comment by ftrrtf** [comment]
@wsromek yeah, sorry for this kind of error. That's why I'm working on the integration test for the bundle now, otherwise — very difficult to check everything on all versions of symfony.

Fixed, check `1.0.0-alpha4` version.

**Comment by wsromek** [comment]
Thank you!
As to kind of error, I know, don't worry:) 
if we only had a little less work, we'd probably fix it ourselves and post a PR :)
