### ISSUE TITLE
Class 'Twig_Function_Method' not found

### ISSUE THREAD

**Issue by Avtonom** [ftrrtf/FtrrtfRollbarBundle#29]
Attempted to load class "Twig_Function_Method" from the global namespace.
File "/vendor/ftrrtf/rollbar-bundle/Twig/RollbarExtension.php" line 47
becose: https://github.com/ftrrtf/FtrrtfRollbarBundle/blob/master/composer.json#L23

**Comment by ftrrtf** [comment]
@Avtonom Just try to remove `notifier.client` section from the configuration to disable twig extensions autoloading. 

https://github.com/ftrrtf/FtrrtfRollbarBundle/blob/master/DependencyInjection/FtrrtfRollbarExtension.php#L30-L38

**Comment by Avtonom** [comment]
@ftrrtf Thanks!
