### ISSUE TITLE
Deprecated classes and methods Symfony 2.8

### ISSUE THREAD

**Issue by OxCom** [ftrrtf/FtrrtfRollbarBundle#33]
Please, update Your code to avoid such notifications.

- The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0:
./vendor/ftrrtf/rollbar-bundle/EventListener/RollbarListener.php
./vendor/ftrrtf/rollbar-bundle/spec/Ftrrtf/RollbarBundle/EventListener/RollbarListenerSpec.php

v0.15.2
Thank You

**Comment by ftrrtf** [comment]
Just tagged (v1.0.0) the latest master, where deprecations have already been deleted
