### ISSUE TITLE
can you please update to latest version of rollbar/rollbar-php?

### ISSUE THREAD

**Issue by cordoval** [ftrrtf/FtrrtfRollbarBundle#34]

**Comment by ftrrtf** [comment]
Yep, working on it, just after first (kinda) stable release of `rollbar/rollbar-php`. 
But migrating from an own client will take some time of course.

**Comment by cordoval** [comment]
too late but 👍 
i am already defining services which is more direct and more powerful, it also let the exception stream downwards through to other handlers.

**Comment by ftrrtf** [comment]
@cordoval btw, be careful with new `rollbar/rollbar-php`, it's still a bit unstable tbh

**Comment by cordoval** [comment]
why you mean unusable? it is perfect and it is working

**Comment by ftrrtf** [comment]
A bit unstable, not unusable. And when there is an error happen in the error logging system, you might not even know about them.
E.g. https://github.com/rollbar/rollbar-php/pull/185, https://github.com/rollbar/rollbar-php/pull/184

**Comment by cordoval** [comment]
one of them was merged, and the other it seems to be me that relates to a file reading and i don't read any file in my case.
