### ISSUE TITLE
Manually report an exception

### ISSUE THREAD

**Issue by eugestarr** [ftrrtf/FtrrtfRollbarBundle#39]
Is there a way to manually report an exception?

Like:
```php
try {
    // do something that may thrown an exception
} catch (Exception $e) {
    $this->rollbar->reportException($e);
    $this->session->getFlashBag()->add('error','Message to user');
}
```

Currently I can't use `vendor/ftrrtf/rollbar-notifier/src/Ftrrtf/Rollbar/Notifier.php` because it's not registered as a valid Symfony service. Any workaround?

**Comment by filipgolonka** [comment]
```
$container->get('ftrrtf_rollbar.notifier')->reportMessage($message, $level);
```
?

**Comment by eugestarr** [comment]
When I inject Notifier to a service (event listener in my case) I get this exception:
```
The service "app.some_listener" has a dependency on a non-existent service "ftrrtf_rollbar.notifier".
```

**Comment by filipgolonka** [comment]
Looks like bundle is not registered in your Symfony app. See README.md: https://github.com/ftrrtf/FtrrtfRollbarBundle#register-the-bundle-in-your-application

**Comment by ftrrtf** [comment]
@eugestarr  I think that the problem with `dev` environment, but the bundle is available only for `prod` one. 

Possible solutions:
1. Register bundle for all environments
2. Make notifier an optional dependency: `@?ftrrtf_rollbar.notifier`
https://symfony.com/doc/current/service_container/optional_dependencies.html

**Comment by eugestarr** [comment]
That was the issue. Bundle was registered for `uat` and `prod` environments only. 

Is there any way to simply disable reporting but keep it running for debug purposes on `dev`, like a flag in a config?

**Comment by eugestarr** [comment]
As a temporary workaround I made it work this way on all environments:

1. Enabled the bundle in `AppKernel.php` for dev

2. Updated yml configuration of the event listener

```yml
app.some_listener:
    class: AppBundle\Listener\SomeListener
    arguments: ["@=container.has('ftrrtf_rollbar.notifier') ? service('ftrrtf_rollbar.notifier') : null"]
    tags:
        - { name: kernel.event_subscriber }
```

3. Updated event listener itself:

```php
class SomeListener implements EventSubscriberInterface
{
    /** @var Notifier */
    private $rollbar;

    /**
     * @param Notifier $rollbar
     */
    public function __construct(Notifier $rollbar = null) // parameter is now optional
    {
        $this->rollbar = $rollbar;
    }

    public static function getSubscribedEvents()
    {
        return [
            Events::REGISTRATION_COMPLETED => 'onRegistrationComplete'
        ];
    }

    /**
     * @param RegistrationCompletedEvent $event
     */
    public function onRegistrationComplete(RegistrationCompletedEvent $event)
    {
        try {
            // do something that may thrown an exception
        } catch (\Exception $e) {
            if ($this->rollbar) { // check if null
                $this->rollbar->reportMessage($e->getMessage(), Notifier::LEVEL_ERROR);
            }
            $this->session->getFlashBag()->add('error','Message to user');
        }
    }
}
```

**Comment by ftrrtf** [comment]
@eugestarr Yep, this is what I advised above.

> Is there any way to simply disable reporting but keep it running for debug purposes on dev

not in the current version

FYI: `"@=container.has('ftrrtf_rollbar.notifier') ? service('ftrrtf_rollbar.notifier') : null" ` can be replaced with simple `@?ftrrtf_rollbar.notifier`
For details look here: https://symfony.com/doc/current/service_container/optional_dependencies.html
